using System.Text.Json;
using FHOOE.Freydis.Agents.Agents.Kuka.Configuration;

namespace FHOOE.Freydis.Agents.Tests.Configuration;

/// <summary>
///     Tests for KUKA iiwa 14 configuration classes and JSON deserialization.
/// </summary>
public class KukaIiwa14ConfigurationTests
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        WriteIndented = true,
        AllowTrailingCommas = true,
        ReadCommentHandling = JsonCommentHandling.Skip
    };

    [Fact]
    public void KukaIiwa14AgentConfiguration_Deserialization_WithValidJson_ShouldSucceed()
    {
        // Arrange
        var json = """
                   {
                       "Agents": [
                           {
                               "Id": "12345678-1234-1234-1234-123456789012",
                               "Name": "KUKA_1",
                               "OpcUaEndpoint": "opc.tcp://localhost:4840/kuka/iiwa14",
                               "Description": "Test KUKA robot",
                               "MaxConcurrentExecutions": 1,
                               "ConnectionTimeout": 10000,
                               "Skills": [
                                   {
                                       "SkillDefinitionId": "87654321-4321-4321-4321-210987654321",
                                       "CanExecuteAdaptively": false,
                                       "NominalDuration": 5.5
                                   }
                               ]
                           }
                       ]
                   }
                   """;

        // Act
        var config = JsonSerializer.Deserialize<KukaIiwa14AgentConfiguration>(json, JsonOptions);

        // Assert
        Assert.NotNull(config);
        Assert.Single(config.Agents);

        var agent = config.Agents[0];
        Assert.Equal(Guid.Parse("12345678-1234-1234-1234-123456789012"), agent.Id);
        Assert.Equal("KUKA_1", agent.Name);
        Assert.Equal("opc.tcp://localhost:4840/kuka/iiwa14", agent.OpcUaEndpoint);
        Assert.Equal("Test KUKA robot", agent.Description);
        Assert.Equal(1, agent.MaxConcurrentExecutions);
        Assert.Equal(10000, agent.ConnectionTimeout);
        Assert.Single(agent.Skills);

        var skill = agent.Skills[0];
        Assert.Equal(Guid.Parse("87654321-4321-4321-4321-210987654321"), skill.SkillDefinitionId);
        Assert.False(skill.CanExecuteAdaptively);
        Assert.Equal(5.5, skill.NominalDuration);
    }

    [Fact]
    public void KukaIiwa14AgentConfiguration_Deserialization_WithMinimalJson_ShouldApplyDefaults()
    {
        // Arrange - minimal configuration with only required fields
        var json = """
                   {
                       "Agents": [
                           {
                               "Name": "KUKA_Minimal",
                               "OpcUaEndpoint": "opc.tcp://localhost:4840",
                               "Skills": []
                           }
                       ]
                   }
                   """;

        // Act
        var config = JsonSerializer.Deserialize<KukaIiwa14AgentConfiguration>(json, JsonOptions);

        // Assert
        Assert.NotNull(config);
        Assert.Single(config.Agents);

        var agent = config.Agents[0];
        Assert.Null(agent.Id); // Will be generated by factory
        Assert.Equal("KUKA_Minimal", agent.Name);
        Assert.Equal("opc.tcp://localhost:4840", agent.OpcUaEndpoint);
        Assert.Null(agent.Description);
        Assert.Equal(1, agent.MaxConcurrentExecutions); // Default value
        Assert.Equal(5000, agent.ConnectionTimeout); // Default value
        Assert.Empty(agent.Skills);
    }

    [Fact]
    public void KukaIiwa14AgentConfiguration_Deserialization_WithMultipleAgents_ShouldDeserializeAll()
    {
        // Arrange
        var json = """
                   {
                       "Agents": [
                           {
                               "Name": "KUKA_1",
                               "OpcUaEndpoint": "opc.tcp://localhost:4841",
                               "Skills": []
                           },
                           {
                               "Name": "KUKA_2",
                               "OpcUaEndpoint": "opc.tcp://localhost:4842",
                               "Skills": []
                           },
                           {
                               "Name": "KUKA_3",
                               "OpcUaEndpoint": "opc.tcp://localhost:4843",
                               "Skills": []
                           }
                       ]
                   }
                   """;

        // Act
        var config = JsonSerializer.Deserialize<KukaIiwa14AgentConfiguration>(json, JsonOptions);

        // Assert
        Assert.NotNull(config);
        Assert.Equal(3, config.Agents.Count);
        Assert.Equal("KUKA_1", config.Agents[0].Name);
        Assert.Equal("KUKA_2", config.Agents[1].Name);
        Assert.Equal("KUKA_3", config.Agents[2].Name);
    }

    [Fact]
    public void KukaIiwa14AgentConfiguration_Deserialization_WithMultipleSkills_ShouldDeserializeAll()
    {
        // Arrange
        var json = """
                   {
                       "Agents": [
                           {
                               "Name": "KUKA_Multi_Skill",
                               "OpcUaEndpoint": "opc.tcp://localhost:4840",
                               "Skills": [
                                   {
                                       "SkillDefinitionId": "11111111-1111-1111-1111-111111111111",
                                       "CanExecuteAdaptively": false,
                                       "NominalDuration": 3.0
                                   },
                                   {
                                       "SkillDefinitionId": "22222222-2222-2222-2222-222222222222",
                                       "CanExecuteAdaptively": false,
                                       "NominalDuration": 5.0
                                   },
                                   {
                                       "SkillDefinitionId": "33333333-3333-3333-3333-333333333333",
                                       "CanExecuteAdaptively": false,
                                       "NominalDuration": 7.5
                                   }
                               ]
                           }
                       ]
                   }
                   """;

        // Act
        var config = JsonSerializer.Deserialize<KukaIiwa14AgentConfiguration>(json, JsonOptions);

        // Assert
        Assert.NotNull(config);
        Assert.Equal(3, config.Agents[0].Skills.Count);
        Assert.Equal(3.0, config.Agents[0].Skills[0].NominalDuration);
        Assert.Equal(5.0, config.Agents[0].Skills[1].NominalDuration);
        Assert.Equal(7.5, config.Agents[0].Skills[2].NominalDuration);
    }

    [Fact]
    public void KukaSkillConfig_WithAdaptiveExecution_ShouldIncludeMinDuration()
    {
        // Arrange
        var json = """
                   {
                       "Agents": [
                           {
                               "Name": "KUKA_Adaptive",
                               "OpcUaEndpoint": "opc.tcp://localhost:4840",
                               "Skills": [
                                   {
                                       "SkillDefinitionId": "44444444-4444-4444-4444-444444444444",
                                       "CanExecuteAdaptively": true,
                                       "NominalDuration": 10.0,
                                       "MinAdaptiveDuration": 7.5
                                   }
                               ]
                           }
                       ]
                   }
                   """;

        // Act
        var config = JsonSerializer.Deserialize<KukaIiwa14AgentConfiguration>(json, JsonOptions);

        // Assert
        Assert.NotNull(config);
        var skill = config.Agents[0].Skills[0];
        Assert.True(skill.CanExecuteAdaptively);
        Assert.Equal(10.0, skill.NominalDuration);
        Assert.Equal(7.5, skill.MinAdaptiveDuration);
    }

    [Fact]
    public void KukaSkillConfig_WithNonAdaptiveExecution_ShouldHaveNullMinDuration()
    {
        // Arrange
        var json = """
                   {
                       "Agents": [
                           {
                               "Name": "KUKA_NonAdaptive",
                               "OpcUaEndpoint": "opc.tcp://localhost:4840",
                               "Skills": [
                                   {
                                       "SkillDefinitionId": "55555555-5555-5555-5555-555555555555",
                                       "CanExecuteAdaptively": false,
                                       "NominalDuration": 8.0
                                   }
                               ]
                           }
                       ]
                   }
                   """;

        // Act
        var config = JsonSerializer.Deserialize<KukaIiwa14AgentConfiguration>(json, JsonOptions);

        // Assert
        Assert.NotNull(config);
        var skill = config.Agents[0].Skills[0];
        Assert.False(skill.CanExecuteAdaptively);
        Assert.Equal(8.0, skill.NominalDuration);
        Assert.Null(skill.MinAdaptiveDuration);
    }

    [Fact]
    public void KukaIiwa14AgentConfiguration_Deserialization_WithEmptyAgentsList_ShouldReturnEmptyList()
    {
        // Arrange
        var json = """
                   {
                       "Agents": []
                   }
                   """;

        // Act
        var config = JsonSerializer.Deserialize<KukaIiwa14AgentConfiguration>(json, JsonOptions);

        // Assert
        Assert.NotNull(config);
        Assert.Empty(config.Agents);
    }

    [Fact]
    public void KukaIiwa14AgentConfiguration_Deserialization_WithCaseInsensitiveProperties_ShouldSucceed()
    {
        // Arrange - test case insensitivity
        var json = """
                   {
                       "agents": [
                           {
                               "name": "KUKA_CaseTest",
                               "opcuaendpoint": "opc.tcp://localhost:4840",
                               "description": "Case test",
                               "skills": []
                           }
                       ]
                   }
                   """;

        // Act
        var config = JsonSerializer.Deserialize<KukaIiwa14AgentConfiguration>(json, JsonOptions);

        // Assert
        Assert.NotNull(config);
        Assert.Single(config.Agents);
        Assert.Equal("KUKA_CaseTest", config.Agents[0].Name);
        Assert.Equal("opc.tcp://localhost:4840", config.Agents[0].OpcUaEndpoint);
    }

    [Fact]
    public void KukaIiwa14AgentConfiguration_DefaultConstructor_ShouldInitializeEmptyAgentsList()
    {
        // Act
        var config = new KukaIiwa14AgentConfiguration();

        // Assert
        Assert.NotNull(config.Agents);
        Assert.Empty(config.Agents);
    }

    [Fact]
    public void KukaIiwa14AgentConfig_DefaultValues_ShouldBeCorrect()
    {
        // Act
        var config = new KukaIiwa14AgentConfig
        {
            Name = "Test",
            OpcUaEndpoint = "opc.tcp://localhost:4840"
        };

        // Assert
        Assert.Null(config.Id);
        Assert.Null(config.Description);
        Assert.Equal(1, config.MaxConcurrentExecutions);
        Assert.Equal(5000, config.ConnectionTimeout);
        Assert.NotNull(config.Skills);
        Assert.Empty(config.Skills);
    }

    [Fact]
    public void KukaSkillConfig_DefaultValues_ShouldBeNull()
    {
        // Act
        var config = new KukaSkillConfig
        {
            CanExecuteAdaptively = false,
            NominalDuration = 5.0
        };

        // Assert
        Assert.Null(config.SkillDefinitionId);
        Assert.Null(config.MinAdaptiveDuration);
    }
}